import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
import Product from '../components/Products';
import {Gallery} from "../styles/Gallery"

export default function Home() {
  
  //fetch from strrapi using graphql
  //Array destructuring
  const [results] = useQuery({query:PRODUCT_QUERY});
  
  //object destructuring
  const {data,fetching,error} = results;
  if(fetching){
    return <p>Loading...</p>
  }
  if(error){
    return <p>error has occured</p>
  }
  const products = data.products.data;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Gebeya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Gallery>
        {products.map((product) => (
          <Product key={product.attributes.slug} product={product} />
        ))
        }
      </Gallery>
        
      

      
    </div>
  )
}
